return {
	Images = {
		slot = "rbxassetid://88913274898382",
		title = "rbxassetid://97179204460094",
		search = "rbxassetid://136059330203007",
		itemGrid = "rbxassetid://125049761045553",
		searchIcon = "rbxassetid://74843870512408",
		background = "rbxassetid://75306024394855",
	},
	Colors = {
		common = Color3.fromHex("5F6263"),
		white = Color3.fromHex("CFD5D8"),
		background = Color3.fromHex("424445"),
		darkerBackground = Color3.fromHex("29292A"),
	},
}
